compute:

  train:
    name: processing-job
    instance: t2.xlarge           
    datastore_name: ck3-portraits       
    datastore_version: 1      
    datastore_mount_dir: /datastores/ck3-portraits    
    use_spot: false           