compute:

  train:
    instance: t2.large           
    datastore_name: ck3-portraits       
    datastore_version: 1      
    datastore_mount_dir: /datastores/ck3-portraits    
    use_spot: false           